### ISSUE TITLE
Cannot restore semanticsdb by the version difference.

### ISSUE THREAD

**Issue by wonhyukc** [MicrosoftDocs/sql-docs.ko-kr#105]
메시지 3169, 수준 16, 상태 1, 줄 1
The database was backed up on a server running version 14.00.0700. That version is incompatible with this server, which is running version 14.00.3048. Either restore the database on a server that supports the backup, or use a backup that is compatible with this server.
메시지 3013, 수준 16, 상태 1, 줄 1
RESTORE DATABASE is terminating abnormally.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a804984c-ad78-db28-3865-d34a71806770
* Version Independent ID: aa5ccdc1-8b7b-da83-4e50-b8afe7f76135
* Content: [Linux에서 SQL Server 전체 텍스트 검색 설치 - SQL Server](https://docs.microsoft.com/ko-kr/sql/linux/sql-server-linux-setup-full-text-search?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-full-text-search.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/linux/sql-server-linux-setup-full-text-search.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by CeciAc** [comment]
안녕하세요, @wonhyukc 
 귀하의 기여에 매우 감사 드립니다. 당사의 팀만이 설명서와 관련된 피드백에 응답할 수 있습니다. 
 DOCS 페이지 하단에 있는 "제품 피드백 제공" 버튼을 사용하여 귀하의 제품 피드백을 기록해주세요. 
 설명서와 관련된 피드백이 있는 경우 이 채널을 통해 자유롭게 기록해주세요. 
 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다.
Microsoft DOCS 국제 팀

**Comment by dougrday** [comment]
이것에 대한 어떤 업데이 트?
