### ISSUE TITLE
When no domain, what should I write ?

### ISSUE THREAD

**Issue by wonhyukc** [MicrosoftDocs/sql-docs.ko-kr#106]
vim /var/opt/mssql/.tlogcreds
#Paste the following in .tlogcreds
username=mssql
domain=&lt;domain&gt;
password=&lt;password&gt;

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: ae3bc9b9-65f5-13bb-53c5-ed929a94b638
* Version Independent ID: eccef86a-10ea-2bbb-ab1b-c530b3fb758c
* Content: [Linux의 SQL Server에 대 한 로그 전달 구성 - SQL Server](https://docs.microsoft.com/ko-kr/sql/linux/sql-server-linux-use-log-shipping?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-use-log-shipping.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/linux/sql-server-linux-use-log-shipping.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @meet-bhagdev
* Microsoft Alias: **meetb**

**Comment by CeciAc** [comment]
Hello, @wonhyukc 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
