### ISSUE TITLE
번역

### ISSUE THREAD

**Issue by aeoragie** [MicrosoftDocs/sql-docs.ko-kr#109]
최종 결과는 57921이 아니라 123457입니다. &gt;&gt; 최종 결과는 123457이 아니라 57921입니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 21a99510-f01a-ee68-6890-4d8b6b25ee38
* Version Independent ID: db555cbb-e0fe-c7d8-eb0d-84b759ac141d
* Content: [binary 및 varbinary(Transact-SQL) - SQL Server](https://docs.microsoft.com/ko-kr/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/data-types/binary-and-varbinary-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/t-sql/data-types/binary-and-varbinary-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by CeciAc** [comment]
안녕하세요. , @aeoragie 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요. , @aeoragie 님.  

 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-2017#feedback에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
