### ISSUE TITLE
번역 오류

### ISSUE THREAD

**Issue by dystarry** [MicrosoftDocs/sql-docs.ko-kr#112]
(원문) just because data lives in-memory does not mean you lose it when there is a failure.

(번역) 데이터가 메모리 내에 있다는 것은 오류 시 손실되지 않음을 의미하는 것이 아닙니다.

(바로 잡음) 데이터가 단지 메모리 내에 있다고해서 오류 시 손실되는 것을 의미하는 것은 아닙니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 6f91f89b-5196-0ea5-28fc-79cf59ab327e
* Version Independent ID: 0f4f2d0d-0913-8b47-15ab-7300dc2aa1a3
* Content: [개요 및 사용 시나리오 - SQL Server](https://docs.microsoft.com/ko-kr/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/overview-and-usage-scenarios.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/relational-databases/in-memory-oltp/overview-and-usage-scenarios.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @jodebrui
* Microsoft Alias: **jodebrui**

**Comment by srvbpigh** [comment]
Hello, @dystarry
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @dystarry 님.
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios?view=sql-server-2017#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
