### ISSUE TITLE
번역 교정

### ISSUE THREAD

**Issue by dystarry** [MicrosoftDocs/sql-docs.ko-kr#113]
(원문) A nonclustered index is preferable over a hash index
(번역) 비클러스터형 인덱스가 해시 인덱스 전체에서 선호됩니다.
(교정) 비클러스터형 인덱스가 해시 인덱스보다 선호됩니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 7a9c5960-23d2-409d-1899-9bd8e079c217
* Version Independent ID: 5626e74a-6059-ab65-5564-cf18208f0038
* Content: [메모리 액세스에 최적화된 테이블의 인덱스 - SQL Server](https://docs.microsoft.com/ko-kr/sql/relational-databases/in-memory-oltp/indexes-for-memory-optimized-tables?view=sql-server-2017)
* Content Source: [docs/relational-databases/in-memory-oltp/indexes-for-memory-optimized-tables.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/relational-databases/in-memory-oltp/indexes-for-memory-optimized-tables.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by srvbpigh** [comment]
Hello, @dystarry
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by MightyPen** [comment]
@CeciAc  There is not enough info here in Issue #113 (sql-docs.ko-kr) for this to be actionable.
Maybe the customer can add another Comment box here, or we may have to close this as non-actionable.
Thanks. (GeneMi)

**Comment by CeciAc** [comment]
@MightyPen this is a linguistic issue, we are working on it :)

**Comment by CeciAc** [comment]
안녕하세요, @dystarry님.
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/sql/relational-databases/in-memory-oltp/indexes-for-memory-optimized-tables?view=sql-server-2017 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
