### ISSUE TITLE
A broken page

### ISSUE THREAD

**Issue by Maxpia** [MicrosoftDocs/sql-docs.ko-kr#115]
[여기에 피드백 입력]
A broken page

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: def018a8-998c-90ab-a82d-c3204ca79121
* Version Independent ID: 4142171c-62c8-8c23-88a1-aeffc43b7523
* Content: [sp_addumpdevice (Transact-sql) - SQL Server](https://docs.microsoft.com/ko-kr/sql/relational-databases/system-stored-procedures/sp-addumpdevice-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-addumpdevice-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/relational-databases/system-stored-procedures/sp-addumpdevice-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srvbpigh** [comment]
Hello, @Maxpia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @Maxpia 

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team
