### ISSUE TITLE
sql graph

### ISSUE THREAD

**Issue by mh-data** [MicrosoftDocs/sql-docs.ko-kr#116]
[여기에 피드백 입력]

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 4a893981-46bb-c010-6d63-39eee88dcf91
* Version Independent ID: 8bacd3f7-6793-3316-6a31-3e599d209821
* Content: [그래프 처리 중 - SQL Server and Azure SQL Database](https://docs.microsoft.com/ko-kr/sql/relational-databases/graphs/sql-graph-overview?view=sql-server-ver15)
* Content Source: [docs/relational-databases/graphs/sql-graph-overview.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/relational-databases/graphs/sql-graph-overview.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by srvbpigh** [comment]
Hello, @mh-data
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요. @mh-data  님, 

댓글을 남겨 주셔서 감사드리며 Microsoft는 docs.microsoft.com의 환경을 개선하기 위해 노력하고 있습니다. 그러나 귀하의 의견을 처리하기 위해서는 추가 정보가 필요합니다. 자세한 정보를 제공하고 댓글에 대해 명확하게 설명해 주실 수 있으신지요? 

감사합니다. 

Microsoft DOCS International 팀

**Comment by mh-data** [comment]
The feedback has been registered by mistake.
Please close the issue.

Thanks.

**Comment by V-vafune** [comment]
Hello, @mh-data , 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations. 

We encourage you to provide your valuable feedback so that we can continue improve your experience. 

Kind regards, 
Microsoft DOCS International Team
