### ISSUE TITLE
In my primary language, table is shown broken if the option "Read it in ENGLISH" enabled.

### ISSUE THREAD

**Issue by Park-minkyu** [MicrosoftDocs/sql-docs.ko-kr#118]
In following URL, You can see the table is broken.

https://docs.microsoft.com/ko-kr/sql/relational-databases/system-catalog-views/sys-database-query-store-options-transact-sql?view=sql-server-ver15
--
SQL Database Basic 버전의 경우 기본값은 7일입니다.For SQL Database Basic edition, default is 7 days.

Change by using the ALTER DATABASE &lt;database&gt; SET QUERY_STORE ( CLEANUP_POLICY = ( STALE_QUERY_THRESHOLD_DAYS = &lt;value&gt; ) ) statement.		

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e40ed537-2f4c-3b03-a252-638a631cedbb
* Version Independent ID: 48519e28-59a6-dda6-40df-004b1bc1d4d9
* Content: [sys. database_query_store_options (Transact-sql) - SQL Server](https://docs.microsoft.com/ko-kr/sql/relational-databases/system-catalog-views/sys-database-query-store-options-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-database-query-store-options-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/relational-databases/system-catalog-views/sys-database-query-store-options-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by Park-minkyu** [comment]
Sorry, Without READ it in ENGLISH Option table is still shown broken.
which means table is originally broken from the beginning.

**Comment by srvbpigh** [comment]
Hello, @Park-minkyu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @Park-minkyu 

Thank you for your feedback.

We cannot replicate the error, is it still visible on your side? 
Are you having the same issue in a different browser?
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Park-minkyu** [comment]
![image](https://user-images.githubusercontent.com/56732077/78847082-bc15ca00-7a48-11ea-82f7-e8d2559fff37.png)

as we can see in this screenshot. table row is not in appropriate state.

**Comment by Park-minkyu** [comment]
in addition, even I enable the READ IT IN ENGLISH option, contents in row won't show in english.

**Comment by Park-minkyu** [comment]
@CeciAc Sorry I forgot to mention you I have attached screenshot.

**Comment by CeciAc** [comment]
Hello @Park-minkyu

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
