### ISSUE TITLE
we need more references for driver version verification 

### ISSUE THREAD

**Issue by Park-minkyu** [MicrosoftDocs/sql-docs.ko-kr#119]
hello, I think that we need more references for verification the version of driver.

we're planning to move log shipping to ag for protecting data from  hardware incidents.
and what people keep asking me is below

"Where Can I confirm the version of ole db driver that I'm using? I think I may use ole db driver but not sure.. you have any idea where to find it?"
"I don't know... go to odbc..."

so what we need is that 
* how to confirm which version of driver that application use.
or
* where to find which driver that application may use.
or
* how to find sessions or connections that uses which version and what type of drivers by query.
Thank you.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 93dc3f31-08df-0ca2-2793-e8abe4de193a
* Version Independent ID: cebd12d7-aedc-f24f-79d3-c2361aa535ec
* Content: [가용성 그룹에 대한 드라이버 및 클라이언트 연결 지원 - SQL Server Always On](https://docs.microsoft.com/ko-kr/sql/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Park-minkyu thank you for reaching out! Drivers are decided by the client and application and are therefore outside the scope of SQL Server. As such, we minimize documenting driver interaction on the SQL side of our docs, as that will be in the driver documentation. 

This blog may provide more insight: http://sqlvandalism.com/2017/03/22/what-client-provider-am-i-using-to-connect-to-sql-server/

I hope that helps and please let us know if you have any questions or concerns.

Thanks!
Masha from the SQL Docs team

**Comment by Park-minkyu** [comment]
Thank you for your feedback!! 
I'm so haapy to hear anything from you!

anyway,
technically you are right what i'm asking is the outside of the scope SQL Driver.

but we're planning to move our ha from Logshipping to AG Standard.
We have a lot of things to pre-check and driver version is the one of the key factor to move on to AG.
and one of my client ask to how to find driver version they are using and I was checking the session dmv and found OLEDB or ODBC had no detailed version information.

and I was starting to think "How can I check what version of SQL driver they are using to connect? If I know the easy way to determine  the driver version client are using at the server side I don't need to ask them to check the driver version. 

All I need to ask is that    "You're using lower version of ODBC Driver , please update ODBC Driver version above 17 to use multisubnetfailover property."

I hope my intention are get to you.

**Comment by MashaMSFT** [comment]
Hi @Park-minkyu ,

You can use the ODBC Data Source Administrator to determine the ODBC driver version: 
![image](https://user-images.githubusercontent.com/32783170/91740135-b8095680-eb67-11ea-89e8-c8166a3b7236.png)

However, to clarify, are you asking for the product to notify you if  the client is connecting with a driver that does not support  multisubnetfailover? 

Thanks!
Masha from the SQL Docs team

**Comment by Park-minkyu** [comment]
@MashaMSFT 
hi masha!!
of course I'm not asking you the name of product.
what i'm asking you is easy way to confirm a version or a name of driver of current query session are using.

**Comment by Park-minkyu** [comment]
like column name of dmv or queries.. what ever it is not a commercial product.

**Comment by MashaMSFT** [comment]
Hi @park-minkyu, thanks again for reaching out! 

If I'm understanding correctly, you're requesting a feature within SQL Server so that you can identify the driver version of a client connection from an active session using a DMV. Is that correct? If so, that is certainly valuable feedback! However, I would encourage you to share it with the product group directly: https://aka.ms/sqlfeedback

I am happy to pass along your recommendation as well, but submitting your feedback allows other customers to vote and add their own comments, providing necessary justification to the product group. 

I hope that helps and please let me know if there is anything I can help you with from the documentation perspective? 

Thanks!
Masha from the SQL Docs team

**Comment by Park-minkyu** [comment]
Hello @MashaMSFT 
exactly! you are right! 

I actually wrote few suggestions on that sql feedback sites.
but it never comes back again. 

So that is why I wrote this questions on this feedback page is way more faster that sql feedback site.
anyway thank you for your feedback and also your answer means that at this point no dmvs or something in-side sql feature to confirm client connection details.

**Comment by MashaMSFT** [comment]
Hi @Park-minkyu , though the product group may not readily respond via the feedback channel, they triage and take that feedback seriously. However, they do end up having to prioritize so they may not be able to implement everything all the time :) 

I've passed along your feedback to the PG as well, so at least they're hearing your feedback from multiple channels!

Thanks again for reaching out, and my apologies we could not do more for you from the doc side. 

I'm going to close out this Git Issue but please feel free to comment should you need anything further.

Thanks and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close

**Comment by Park-minkyu** [comment]
@MashaMSFT 
Thanks for your kind feedback,
I'll post my idea on sql azure feedback page and close this issue.
Though this is simple idea but you answered so kindly and repeatedly.

Thank you again.

**Comment by MashaMSFT** [comment]
@Park-minkyu 
no problem at all, we're here to help :) thanks for reaching out!

**Comment by Park-minkyu** [comment]
@MashaMSFT 
FYI
Here is my Connect suggestion(or report whatever) list(well, not using this name anymore)
* https://feedback.azure.com/forums/908035-sql-server/suggestions/32895931-extended-events-creates-dump-when-destination-file
* https://feedback.azure.com/forums/908035-sql-server/suggestions/34032724-ceip-service-cause-noisy-error-log
* https://feedback.azure.com/forums/908035-sql-server/suggestions/34488658-smo-script-bug-cannot-drop-table-sver
* https://feedback.azure.com/forums/908035-sql-server/suggestions/36399613-deprecated-startup-parameter-t9678
* **_https://feedback.azure.com/forums/908035-sql-server/suggestions/41291308-require-dmvs-that-gives-detailed-client-driver-inf_**

**Comment by MashaMSFT** [comment]
@Park-minkyu , thanks for this! I'll personally send them over to the PG as well 👍 

Thanks!
Masha from the SQL Docs team
